apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: gardenlinux-repo
spec:
  type: git
  params:
    - name: revision
      value: refactor-integrationtests-pipeline
    - name: url
      value: https://github.com/gardenlinux/gardenlinux.git
