# Demo TaskRun showing how to invoke the integration-test Task "standalone" for aws, without a pipeline
apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  generateName: it-test-aws-
spec:
  serviceAccountName: build-bot
  taskRef:
    name: integrationtest-gardenlinux-task
  params:
  - name: iaas
    value: aws
  - name: ami_id
    value: ami-0e7e5773a975f0aea
  resources:
    inputs:
    - name: repo
      resourceRef:
        name: gardenlinux-repo