# Pipeline that runs the integrationtests for all iaas providers in parallel
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: integrationtests-all
spec:
  params:
  - name: ami_id
    type: string
  - name: gcp_image_name
    type: string
  resources:
  - name: source-repo
    type: git
  tasks:
  - name: integrationtest-aws
    taskRef:
      name: integrationtest-gardenlinux-task
    params:
    - name: iaas
      value: aws
    - name: ami_id
      value: $(params.ami_id)
    resources:
      inputs:
      - name: repo
        resource: source-repo
  - name: integrationtest-gcp
    taskRef:
      name: integrationtest-gardenlinux-task
    params:
    - name: iaas
      value: gcp
    - name: gcp_image_name
      value: $(params.gcp_image_name)
    resources:
      inputs:
        - name: repo
          resource: source-repo